/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const ProfileBS = require('./Profile.bs');

// tslint:disable-next-line:interface-over-type-literal
export type Props = {};

export const $$default: React.ComponentType<{}> = ProfileBS.default;

export default $$default;
