/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const AppBS = require('./App.bs');

// tslint:disable-next-line:interface-over-type-literal
export type app_Props = {};

export const app: React.ComponentType<{}> = AppBS.app;
